language: php

php:
  - 5.6.29

install:
  - composer selfupdate
  - composer install

script:
  - vendor/bin/phpcs -s
  - vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls